name: telegram message
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Telegram Message Notify
        uses: appleboy/telegram-action@master
        with:
          if: github.event_name != 'pull_request'
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          message: |
            A new PR is raised View all PR's ${{ GITHUB_REF }}
