name: telegram message
on:
  pull_request:
    types: [opened, reopened, ready_for_review, closed]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Telegram Message Notify
        uses: appleboy/telegram-action@master
        env:
          BRANCH_NAME: ${{ github.head_ref || github.ref_name }} 
        with:
          if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          message: |
            A new PR is ${{github.head_ref}} View all PR's ${{ github.prNumber }} ${{BRANCH_NAME}}
