name: telegram message
on:
  pull_request:
    types: [opened, reopened, ready_for_review, closed]
env:
  PR_NUMBER: ${{ github.event.number }}
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Telegram Message Notify
        uses: appleboy/telegram-action@master
        with:
          if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          message: |
            A new PR ${{ github.ref }} View all PR's ${{ PR_NUMBER }}
